In [3]:
import numpy as np

In [4]:
%time myarr = np.arange(1000000)
%time mylist = list(range(1000000))

CPU times: user 2.35 ms, sys: 248 µs, total: 2.6 ms
Wall time: 1.78 ms
CPU times: user 22 ms, sys: 19.9 ms, total: 41.8 ms
Wall time: 41.4 ms


In [5]:
%time for _ in range(10): myarr2 = myarr * 2
%time for _ in range(10): mylist2 = [x * 2 for x in mylist]

CPU times: user 14.8 ms, sys: 292 µs, total: 15.1 ms
Wall time: 14.1 ms
CPU times: user 673 ms, sys: 121 ms, total: 794 ms
Wall time: 794 ms


In [9]:
arraleatorio = np.random.randn(2,3)
print(arraleatorio)
arraleatorio = arraleatorio * 10
print(arraleatorio)
arraleatorio = arraleatorio + arraleatorio
print(arraleatorio)
print(arraleatorio.shape)
print(arraleatorio.dtype)

[[-0.77632758  1.19018131 -0.98976616]
 [ 0.654997    1.04841297 -1.25281808]]
[[ -7.76327578  11.90181309  -9.89766158]
 [  6.54996999  10.48412967 -12.5281808 ]]
[[-15.52655156  23.80362617 -19.79532316]
 [ 13.09993998  20.96825934 -25.0563616 ]]
(2, 3)
float64


In [10]:
arr1 = np.array([6,7.5,8,0,1])
print(arr1)

[6.  7.5 8.  0.  1. ]
