In [3]:
import numpy as np

In [4]:
%time myarr = np.arange(1000000)
%time mylist = list(range(1000000))

CPU times: user 2.35 ms, sys: 248 µs, total: 2.6 ms
Wall time: 1.78 ms
CPU times: user 22 ms, sys: 19.9 ms, total: 41.8 ms
Wall time: 41.4 ms


In [5]:
%time for _ in range(10): myarr2 = myarr * 2
%time for _ in range(10): mylist2 = [x * 2 for x in mylist]

CPU times: user 14.8 ms, sys: 292 µs, total: 15.1 ms
Wall time: 14.1 ms
CPU times: user 673 ms, sys: 121 ms, total: 794 ms
Wall time: 794 ms


In [9]:
arraleatorio = np.random.randn(2,3)
print(arraleatorio)
arraleatorio = arraleatorio * 10
print(arraleatorio)
arraleatorio = arraleatorio + arraleatorio
print(arraleatorio)
print(arraleatorio.shape)
print(arraleatorio.dtype)

[[-0.77632758  1.19018131 -0.98976616]
 [ 0.654997    1.04841297 -1.25281808]]
[[ -7.76327578  11.90181309  -9.89766158]
 [  6.54996999  10.48412967 -12.5281808 ]]
[[-15.52655156  23.80362617 -19.79532316]
 [ 13.09993998  20.96825934 -25.0563616 ]]
(2, 3)
float64


In [11]:
arr1 = np.array([6,7.5,8,0,1])
print(arr1)
print(arr1.ndim)
print(arr1.shape)
print(arr1.dtype)

[6.  7.5 8.  0.  1. ]
1
(5,)
float64


In [14]:
arrzeros = np.zeros(10)
print(arrzeros)
arrzeros = np.zeros((3, 6))
print(arrzeros)
arrones = np.ones((3,6))
print(arrones)
arrfull = np.full((3,6), 9)
print(arrfull)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
[[9 9 9 9 9 9]
 [9 9 9 9 9 9]
 [9 9 9 9 9 9]]


In [17]:
arrempty = np.empty((2,3,2))
print(arrempty)

[[[6.94883067e-310 4.67423785e-310]
  [2.10077583e-312 6.79038654e-313]
  [2.22809558e-312 2.14321575e-312]]

 [[2.35541533e-312 6.79038654e-313]
  [2.22809558e-312 2.14321575e-312]
  [2.46151512e-312 2.41907520e-312]]]


In [18]:
arreye = np.eye(3)
print(arreye)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [19]:
arr1 = np.array([1,2,3], dtype=np.float64)
print(arr1.dtype)
arr2 = np.array([1,2,3], dtype=np.int32)
print(arr2.dtype)

float64
int32


In [20]:
numeric_string = np.array(['1.25', '-9.6', '4.2'], dtype=np.string_)
numeric_float = numeric_string.astype(float)
print(numeric_float.dtype)
print(numeric_string)
print(numeric_float)

float64
[b'1.25' b'-9.6' b'4.2']
[ 1.25 -9.6   4.2 ]


In [21]:
arr = np.array([[1.,2.,3.],[4.,5.,6.]])
print(arr)
print(arr * arr)
print(arr - arr)
print(1 / arr)
print(arr ** 0.5)

[[1. 2. 3.]
 [4. 5. 6.]]
[[ 1.  4.  9.]
 [16. 25. 36.]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]


In [22]:
arr2 = np.array([[0.,4.,1.], [7.,2.,12.]])
print(arr > arr2)
print(arr == arr2)

[[ True False  True]
 [False  True False]]
[[False False False]
 [False False False]]


In [25]:
arr = np.arange(10)
print(arr)
print(arr[5]) # Ele irá pegar a partir do 5 elemento
print(arr[5:8])
arr[5:8] = 12
print(arr)
# Neste caso será copiado a referência da memória
# Não será feita a cópia
arr2 = arr[5:8]
print(arr2)
arr2[1] = 30
print(arr2)
print(arr)

[0 1 2 3 4 5 6 7 8 9]
5
[5 6 7]
[ 0  1  2  3  4 12 12 12  8  9]
[12 12 12]
[12 30 12]
[ 0  1  2  3  4 12 30 12  8  9]


In [27]:
arr2d = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(arr2d[2])
print(arr2d[0][2])
print(arr2d[0,2])

[7 8 9]
3
3


In [31]:
arr2copia = arr2d[2].copy()
arr2copia[:] = 200
print(arr2d)
print(arr2copia)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[200 200 200]


In [33]:
arr = np.arange(10)
print(arr)
print(arr[1:6])
print(arr[:2])
arr2d = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(arr2d)
print(arr2d[:2,1:])

[0 1 2 3 4 5 6 7 8 9]
[1 2 3 4 5]
[0 1]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2 3]
 [5 6]]


In [39]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
print(names)
data = np.random.randn(7,4)
print(data)
print(names == 'Bob')
print(data[names == 'Bob'])
print(data[names == 'Bob', 2:])

['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
[[-0.48118984 -0.57276941  0.15774105  0.27847209]
 [-0.04118533 -0.6058873  -0.7801684  -1.18764918]
 [-0.42386532  0.01429586  0.37758958  2.55547495]
 [-1.10286671 -0.83310731  0.39565929 -0.5033583 ]
 [-0.78054435 -0.68692043  0.60049357  0.21989476]
 [-1.52965003 -1.35073902  0.9553373   0.27758568]
 [ 0.40031237  0.27704483  0.88788361  1.09915578]]
[ True False False  True False False False]
[[-0.48118984 -0.57276941  0.15774105  0.27847209]
 [-1.10286671 -0.83310731  0.39565929 -0.5033583 ]]
[[ 0.15774105  0.27847209]
 [ 0.39565929 -0.5033583 ]]


In [40]:
print(data[~(names == 'Bob')])

[[-0.04118533 -0.6058873  -0.7801684  -1.18764918]
 [-0.42386532  0.01429586  0.37758958  2.55547495]
 [-0.78054435 -0.68692043  0.60049357  0.21989476]
 [-1.52965003 -1.35073902  0.9553373   0.27758568]
 [ 0.40031237  0.27704483  0.88788361  1.09915578]]


In [41]:
cond = (names == 'Bob') | (names == 'Will')
print(data[cond])

[[-0.48118984 -0.57276941  0.15774105  0.27847209]
 [-0.42386532  0.01429586  0.37758958  2.55547495]
 [-1.10286671 -0.83310731  0.39565929 -0.5033583 ]
 [-0.78054435 -0.68692043  0.60049357  0.21989476]]


In [43]:
data[data < 0] = 0
print(data)

[[0.         0.         0.15774105 0.27847209]
 [0.         0.         0.         0.        ]
 [0.         0.01429586 0.37758958 2.55547495]
 [0.         0.         0.39565929 0.        ]
 [0.         0.         0.60049357 0.21989476]
 [0.         0.         0.9553373  0.27758568]
 [0.40031237 0.27704483 0.88788361 1.09915578]]


In [47]:
arr = np.empty((8,4))
for i in range(8):
    arr[i] = i
print(arr)
print(arr[[4,3,0,6]])
print(arr[[-3,-5,-7]])

[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]
 [5. 5. 5. 5.]
 [6. 6. 6. 6.]
 [7. 7. 7. 7.]]
[[4. 4. 4. 4.]
 [3. 3. 3. 3.]
 [0. 0. 0. 0.]
 [6. 6. 6. 6.]]
[[5. 5. 5. 5.]
 [3. 3. 3. 3.]
 [1. 1. 1. 1.]]


In [50]:
arr = np.arange(32).reshape(8,4)
print(arr)
print(arr[[1,5,7,2],[0,3,1,2]])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
[ 4 23 29 10]


In [51]:
arr = np.arange(15).reshape((3,5))
print(arr)
print(arr.T)
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
