In [3]:
import numpy as np

In [4]:
%time myarr = np.arange(1000000)
%time mylist = list(range(1000000))

CPU times: user 2.35 ms, sys: 248 µs, total: 2.6 ms
Wall time: 1.78 ms
CPU times: user 22 ms, sys: 19.9 ms, total: 41.8 ms
Wall time: 41.4 ms


In [5]:
%time for _ in range(10): myarr2 = myarr * 2
%time for _ in range(10): mylist2 = [x * 2 for x in mylist]

CPU times: user 14.8 ms, sys: 292 µs, total: 15.1 ms
Wall time: 14.1 ms
CPU times: user 673 ms, sys: 121 ms, total: 794 ms
Wall time: 794 ms


In [9]:
arraleatorio = np.random.randn(2,3)
print(arraleatorio)
arraleatorio = arraleatorio * 10
print(arraleatorio)
arraleatorio = arraleatorio + arraleatorio
print(arraleatorio)
print(arraleatorio.shape)
print(arraleatorio.dtype)

[[-0.77632758  1.19018131 -0.98976616]
 [ 0.654997    1.04841297 -1.25281808]]
[[ -7.76327578  11.90181309  -9.89766158]
 [  6.54996999  10.48412967 -12.5281808 ]]
[[-15.52655156  23.80362617 -19.79532316]
 [ 13.09993998  20.96825934 -25.0563616 ]]
(2, 3)
float64


In [11]:
arr1 = np.array([6,7.5,8,0,1])
print(arr1)
print(arr1.ndim)
print(arr1.shape)
print(arr1.dtype)

[6.  7.5 8.  0.  1. ]
1
(5,)
float64


In [14]:
arrzeros = np.zeros(10)
print(arrzeros)
arrzeros = np.zeros((3, 6))
print(arrzeros)
arrones = np.ones((3,6))
print(arrones)
arrfull = np.full((3,6), 9)
print(arrfull)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
[[9 9 9 9 9 9]
 [9 9 9 9 9 9]
 [9 9 9 9 9 9]]


In [17]:
arrempty = np.empty((2,3,2))
print(arrempty)

[[[6.94883067e-310 4.67423785e-310]
  [2.10077583e-312 6.79038654e-313]
  [2.22809558e-312 2.14321575e-312]]

 [[2.35541533e-312 6.79038654e-313]
  [2.22809558e-312 2.14321575e-312]
  [2.46151512e-312 2.41907520e-312]]]


In [18]:
arreye = np.eye(3)
print(arreye)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [19]:
arr1 = np.array([1,2,3], dtype=np.float64)
print(arr1.dtype)
arr2 = np.array([1,2,3], dtype=np.int32)
print(arr2.dtype)

float64
int32


In [20]:
numeric_string = np.array(['1.25', '-9.6', '4.2'], dtype=np.string_)
numeric_float = numeric_string.astype(float)
print(numeric_float.dtype)
print(numeric_string)
print(numeric_float)

float64
[b'1.25' b'-9.6' b'4.2']
[ 1.25 -9.6   4.2 ]
